kitchen/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from .views import (
    index,
    login_view,
    register_user,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    toggle_assign_to_dish,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
    IngredientListView,
    IngredientCreateView,
    IngredientUpdateView,
    IngredientDeleteView,
    DishTypeListView,
    DishTypeDetailView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
)


app_name = "kitchen"

urlpatterns = [
    path("", index, name="index"),
    path("accounts/login/", login_view, name="login"),
    path('register/', register_user, name="register"),
    path("logout/", LogoutView.as_view(), name="logout"),

    # DishType
    path("dish-types/", DishTypeListView.as_view(), name="dish-type-list"),
    path("dish-types/create/", DishTypeCreateView.as_view(), name="dish-type-create"),
    path("dish-types/<int:pk>/", DishTypeDetailView.as_view(), name="dish-type-detail"),
    path("dishes/<int:pk>/assign/", toggle_assign_to_dish, name="dish-assign-toggle"),
    path("dish-types/<int:pk>/update/", DishTypeUpdateView.as_view(), name="dish-type-update"),
    path("dish-types/<int:pk>/delete/", DishTypeDeleteView.as_view(), name="dish-type-delete"),

    # Ingredients
    path("ingredients/", IngredientListView.as_view(), name="ingredient-list"),
    path("ingredients/create/", IngredientCreateView.as_view(), name="ingredient-create"),
    path("ingredients/<int:pk>/update/", IngredientUpdateView.as_view(), name="ingredient-update"),
    path("ingredients/<int:pk>/delete/", IngredientDeleteView.as_view(), name="ingredient-delete"),

    # Dishes
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path("dishes/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dishes/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path("dishes/<int:pk>/toggle-assign/", toggle_assign_to_dish, name="dish-toggle-assign"),

    # Cooks
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path("cooks/<int:pk>/update/", CookUpdateView.as_view(), name="cook-update"),
    path("cooks/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/accounts/login.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Sign IN {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} sign-in-illustration {% endblock body_class %}

{% block content %}

  {% include "includes/navigation-auth.html" %}
  
  <section>
    <div class="page-header section-height-100">
      <div class="container">
        <div class="row">
          <div class="col-xl-4 col-lg-5 col-md-7 d-flex flex-column mx-lg-0 mx-auto">
            <div class="card card-plain">
              <div class="card-header pb-0 text-left">
                <h4 class="font-weight-bolder">Sign In</h4>
                <p class="mb-0">
                  {% if messages %}
                    {% for message in messages %}
                      <span style="color: #4c51bf; font-weight: 500;">{{ message }}</span>
                    {% endfor %}
                  {% elif msg %}
                    <span style="color: #4c51bf; font-weight: 500;">{{ msg|safe }}</span>
                  {% else %}
                    Add your credentials
                  {% endif %}
                </p>                            
              </div>
              <div class="card-body">

                <form method="post" action="" role="form">

                  {% csrf_token %}

                  <div class="mb-3">
                    {{ form.username }}
                  </div>
                  <div class="mb-3">
                    {{ form.password }}
                  </div>
                  <div class="form-check form-switch">
                    <input class="form-check-input" type="checkbox" id="rememberMe">
                    <label class="form-check-label" for="rememberMe">Remember me</label>
                  </div>
                  <div class="text-center">
                    <button type="submit" name="login" 
                            class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">Sign in</button>
                  </div>
                </form>
              </div>
              <div class="card-footer text-center pt-0 px-lg-2 px-1">
                <p class="mb-4 text-sm mx-auto">
                  Don't have an account?
                  <a href="{% url 'kitchen:register' %}" class="text-primary text-gradient font-weight-bold">Sign UP</a>
                </p>
              </div>
            </div>
          </div>
          <div class="col-6 d-lg-flex d-none h-100 my-auto pe-0 position-absolute top-0 end-0 text-center justify-content-center flex-column">
            <div class="position-relative bg-gradient-primary h-100 m-3 px-7 border-radius-lg d-flex flex-column justify-content-center">
              <img src="{{ ASSETS_ROOT }}/img/shapes/pattern-lines.svg" alt="pattern-lines" class="position-absolute opacity-4 start-0">
              <div class="position-relative">
                <img class="max-width-500 w-100 position-relative z-index-2" src="{{ ASSETS_ROOT }}/img/illustrations/chat.png">
              </div>
              <h4 class="mt-5 text-white font-weight-bolder">
                Restourant Kitchen Service
              </h4>
              <p class="text-white">
                &copy; <a target="_blank" class="text-white" href="https://bit.ly/3fKQZaL" target="_blank">Creative Tim</a> 
                - Coded by <a class="text-white" target="_blank" href="https://bit.ly/3GUiBLT" target="_blank">Max Prykhodko</a>.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}

  <script src="{{ ASSETS_ROOT }}/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>

{% endblock javascripts %}

templates/accounts/register.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Sign UP {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} sign-in-illustration {% endblock body_class %}

{% block content %}

  {% include "includes/navigation-auth.html" %}
  
  <section>
    <div class="page-header section-height-100">
      <div class="container">
        <div class="row">
          <div class="col-xl-4 col-lg-5 col-md-7 d-flex flex-column mx-lg-0 mx-auto">
            <div class="card card-plain">
              <div class="card-header pb-0 text-left">
                <h4 class="font-weight-bolder">Sign UP</h4>
              </div>
              <div class="card-body">
                <form method="post" action="" role="form">

                  {% csrf_token %}
                  
                  <div class="mb-3">
                    {{ form.username }}
                  </div>                
                  <span class="text-error">{{ form.username.errors }}</span>

                  <div class="mb-3">
                    {{ form.email }}
                  </div>
                  <span class="text-error">{{ form.email.errors }}</span>
                  
                  <div class="mb-3">
                    {{ form.password1 }}
                  </div>
                  <span class="text-error">{{ form.password1.errors }}</span>

                  <div class="mb-3">
                    {{ form.password2 }}
                  </div>
                  <span class="text-error">{{ form.password2.errors }}</span>
                  
                  <div class="mb-3">
                    {{ form.first_name }}
                    <span class="text-error">{{ form.first_name.errors }}</span>
                  </div>
                  
                  <div class="mb-3">
                    {{ form.last_name }}
                    <span class="text-error">{{ form.last_name.errors }}</span>
                  </div>
                  
                  <div class="mb-3">
                    {{ form.years_of_experience }}
                    <span class="text-error">{{ form.years_of_experience.errors }}</span>
                  </div>                  
          
                  <div class="form-check form-switch">
                    <input class="form-check-input" type="checkbox" id="rememberMe">
                    <label class="form-check-label" for="rememberMe">
                      Agree with <a href="#">terms</a>
                    </label>
                  </div>
                  <div class="text-center">
                    <button type="submit" name="register"
                            class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">Register</button>
                  </div>
                </form>
              </div>
              <div class="card-footer text-center pt-0 px-lg-2 px-1">
                <p class="mb-4 text-sm mx-auto">
                  Have an account?
                  <a href="{% url 'kitchen:login' %}" class="text-primary text-gradient font-weight-bold">Sign IN</a>
                </p>
              </div>
            </div>
          </div>
          <div class="col-6 d-lg-flex d-none h-100 my-auto pe-0 position-absolute top-0 end-0 text-center justify-content-center flex-column">
            <div class="position-relative bg-gradient-primary h-100 m-3 px-7 border-radius-lg d-flex flex-column justify-content-center">
              <img src="{{ ASSETS_ROOT }}/img/shapes/pattern-lines.svg" alt="pattern-lines" class="position-absolute opacity-4 start-0">
              <div class="position-relative">
                <img class="max-width-500 w-100 position-relative z-index-2" src="{{ ASSETS_ROOT }}/img/illustrations/chat.png">
              </div>
              <h4 class="mt-5 text-white font-weight-bolder">
                Restourant Kitchen Service
              </h4>
              <p class="text-white">
                &copy; <a target="_blank" class="text-white" href="https://bit.ly/3fKQZaL" target="_blank">Creative Tim</a> 
                - Coded by <a class="text-white" target="_blank" href="https://bit.ly/3GUiBLT" target="_blank">Max Prykhodko</a>.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}

  <script src="{{ ASSETS_ROOT }}/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>

{% endblock javascripts %}