kitchen/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from .views import (
    index,
    login_view,
    register_user,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    toggle_assign_to_dish,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
    IngredientListView,
    IngredientCreateView,
    IngredientUpdateView,
    IngredientDeleteView,
    DishTypeListView,
    DishTypeDetailView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
)


app_name = "kitchen"

urlpatterns = [
    path("", index, name="index"),
    path("accounts/login/", login_view, name="login"),
    path('register/', register_user, name="register"),
    path("logout/", LogoutView.as_view(), name="logout"),

    # DishType
    path("dish-types/", DishTypeListView.as_view(), name="dish-type-list"),
    path("dish-types/create/", DishTypeCreateView.as_view(), name="dish-type-create"),
    path("dish-types/<int:pk>/", DishTypeDetailView.as_view(), name="dish-type-detail"),
    path("dishes/<int:pk>/assign/", toggle_assign_to_dish, name="dish-assign-toggle"),
    path("dish-types/<int:pk>/update/", DishTypeUpdateView.as_view(), name="dish-type-update"),
    path("dish-types/<int:pk>/delete/", DishTypeDeleteView.as_view(), name="dish-type-delete"),

    # Ingredients
    path("ingredients/", IngredientListView.as_view(), name="ingredient-list"),
    path("ingredients/create/", IngredientCreateView.as_view(), name="ingredient-create"),
    path("ingredients/<int:pk>/update/", IngredientUpdateView.as_view(), name="ingredient-update"),
    path("ingredients/<int:pk>/delete/", IngredientDeleteView.as_view(), name="ingredient-delete"),

    # Dishes
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path("dishes/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dishes/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path("dishes/<int:pk>/toggle-assign/", toggle_assign_to_dish, name="dish-toggle-assign"),

    # Cooks
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path("cooks/<int:pk>/update/", CookUpdateView.as_view(), name="cook-update"),
    path("cooks/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/footer.html
<footer class="footer pt-5 mt-5">
  <hr class="horizontal dark mb-5">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 text-center mb-4">
        <h6 class="text-gradient text-primary font-weight-bolder">
          Restourant Kitchen Service
        </h6>
      </div>
      <div class="col-md-3 mb-4">
        <div>
          <h6 class="mt-3 mb-2 opacity-8 d-flex justify-content-center">Social</h6>
          <ul class="d-flex flex-row justify-content-center nav">
            <li class="nav-item">
              <a class="nav-link pe-1" href="https://www.facebook.com/CreativeTim/" target="_blank">
                <i class="fab fa-facebook text-lg opacity-8"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link pe-1" href="https://twitter.com/creativetim" target="_blank">
                <i class="fab fa-twitter text-lg opacity-8"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link pe-1" href="https://dribbble.com/creativetim" target="_blank">
                <i class="fab fa-dribbble text-lg opacity-8"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link pe-1" href="https://github.com/creativetimofficial" target="_blank">
                <i class="fab fa-github text-lg opacity-8"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link pe-1" href="https://www.youtube.com/channel/UCVyTG4sCw-rOvB9oHkzZD1w" target="_blank">
                <i class="fab fa-youtube text-lg opacity-8"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>

      <div class="col-12">
        <div class="d-flex justify-content-center">
          <p class="my-4 text-sm text-center">
            Restourant Kitchen Service by &copy; <a target="_blank" href="https://bit.ly/3fKQZaL">Creative Tim</a> 
            - Coded by <a target="_blank" href="https://bit.ly/3GUiBLT">Max Prykhodko</a>.
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>

templates/includes/navigation-auth.html
  <div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid">
            <a class="navbar-brand font-weight-bolder ms-sm-3" 
               href="/" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
              Restourant Kitchen Service
            </a>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>

templates/includes/navigation.html
{% load static %}

  <div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid">
            <a class="navbar-brand font-weight-bolder ms-sm-3" 
               href="/" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
               Restourant Kitchen Service
            </a>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
            </button>
            <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0" id="navigation">
              <ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100 gap-2 fs-6">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="dishesDropdown" data-bs-toggle="dropdown">Dishes</a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'kitchen:dish-list' %}">All Dishes</a></li>
                    <li><a class="dropdown-item" href="{% url 'kitchen:dish-create' %}">Create Dish</a></li>
                  </ul>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="dishTypesDropdown" data-bs-toggle="dropdown">Dish Types</a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'kitchen:dish-type-list' %}">All Dish Types</a></li>
                    <li><a class="dropdown-item" href="{% url 'kitchen:dish-type-create' %}">Create Dish Type</a></li>
                  </ul>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="ingredientsDropdown" data-bs-toggle="dropdown">Ingredients</a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'kitchen:ingredient-list' %}">All Ingredients</a></li>
                    <li><a class="dropdown-item" href="{% url 'kitchen:ingredient-create' %}">Create Ingredient</a></li>
                  </ul>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="cooksDropdown" data-bs-toggle="dropdown">Cooks</a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'kitchen:cook-list' %}">All Cooks</a></li>
                    <li><a class="dropdown-item" href="{% url 'kitchen:cook-create' %}">Create Cook</a></li>
                  </ul>
                </li>  
                <li class="nav-item ms-lg-auto">
                  <a class="nav-link nav-link-icon me-2" href="{% url 'kitchen:logout' %}">
                    <i class="fa fa-sign-out me-1"></i>
                    <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Logout">Logout</p>
                  </a>
                </li>
                {% if user.is_authenticated %}
                  <li class="nav-item my-auto ms-3 ms-lg-0">
                    <div class="text-center text-white ms-3">
                      <div style="color: #4682B4" class="fw-bold text-uppercase">
                        <a href="{% url 'kitchen:cook-detail' user.id %}" class="fw-bold text-uppercase text-decoration-none" style="color: #4682B4">
                          {{ user.username }}
                        </a>
                      </div>
                      <small class="text-muted">
                        {% if user.is_superuser %}admin{% else %}common user{% endif %}
                      </small>
                    </div>
                  </li>
                {% endif %}

              </ul>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>

templates/includes/scripts.html
  <script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/prism.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>